### PR TITLE
Added better test coverage for the activate and deactivate feature

### PR DESCRIPTION
**Pull request by Transmitt0r**
This PR adds additional tests for the provider, since test-coverage was pretty poor. Also take a look at #42, as the issue it fixes ties directly into this PR.

### CODE REVIEW

**Comment by bergie** [comment]
@Transmitt0r can you rebase on master?

**Comment by Transmitt0r** [comment]
Good idea, done!

**Comment by bergie** [comment]
@Transmitt0r FYI there was a little issue with `done` handling, fixed in https://github.com/flowhub/bigiot-js/commit/d65f210d15ea6356d5d6dd49ee9f17260f056102

**Comment by Transmitt0r** [comment]
@bergie Ah thanks, I saw the console ouput but thought it belonged to the skipped tests. I'm still getting familiar with Mocha 😅

**Pull request merged**
